apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-clustersecretstore
spec:
  provider:
    fake:
      data:
        - key: "grafana-athena-datasource"
          value: '{"default_region":"us-east-1","access_key_id":"test-access-key-id-clustersecretstore","secret_access_key":"test-secret-access-key-clustersecretstore","workgroup":"test-workgroup-clustersecretstore","catalog":"test-catalog-clustersecretstore","database":"test-database-clustersecretstore"}'
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-secretstore
  namespace: default
spec:
  provider:
    fake:
      data:
        - key: "grafana-athena-datasource"
          value: '{"default_region":"us-east-2","access_key_id":"test-access-key-id-secretstore","secret_access_key":"test-secret-access-key-secretstore","workgroup":"test-workgroup-secretstore","catalog":"test-catalog-secretstore","database":"test-database-secretstore"}'
